version: '3.8'

networks:
  inception:
    name: inception

services:
  nginx:
    networks:
      - inception
    container_name: nginx
    build: ./requirements/nginx
    image: nginx:alpine
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html/wordpress
    env_file:
      - .env
    restart: 
      always

  mariadb:
    networks:
      - inception
    container_name: mariadb
    build: requirements/mariadb
    image: mariadb:alpine
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    restart: always

  wordpress:
    networks:
      - inception
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:alpine
    depends_on:
      - mariadb
    volumes:
      - wordpress_data:/var/www/html/wordpress
    env_file:
      - .env
    restart: always

volumes:
  db_data:
    driver_opts:
      type: none
      device: /home/yena/data/mysql
      o: bind

  wordpress_data:
    driver_opts:
      type: none
      device: /home/yena/data/wordpress
      o: bind
