version: '3.8'

networks:
  inception:
    name: inception

services:
  mariadb:
    env_file:
      - .env
    container_name: mariadb
    build: requirements/mariadb
    image: mariadb:alpine
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    env_file:
      - .env
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:alpine
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html/wordpress
    restart: always

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "443:443"
    build: ./requirements/nginx
    networks:
      - inception
    env_file:
      - .env
    restart: 
      always

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /home/yena/data/mysql
      o: bind

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/yena/data/wordpress
