version: '3.8'

networks:
  inception:
    name: inception

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    depends_on:
      - wordpress
    ports:
      - "443:443"
    build: ./requirements/nginx
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - wordpress_data:/var/www
    networks:
      - inception
    env_file:
      - .env
    restart: 
      always
  
  mariadb:
    env_file:
      - .env
    container_name: mariadb
    build: requirements/mariadb
    image: mariadb:alpine
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    ports:
      - "3306:3306"
    restart: always

  wordpress:
    env_file:
      - .env
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:alpine
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/
    restart: always

volumes:
  db_data:
    driver_opts:
      type: none
      device: /home/yena/data/mariadb
      o: bind

  wordpress_data:
    driver_opts:
      type: none
      device: /home/yena/data/wordpress
      o: bind
